title: RESTlr
author: "Philipp Kursawe"
baseurl:
host: 0.0.0.0
url: https://restlr.net
email: phil.kursawe+restlr@gmail.com
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
permalink: pretty
exclude: [ 'Rakefile', "node_modules", ".vscode" ]
encoding: utf-8
